/*
 * Copyright 2002-2011 SCOOP Software GmbH
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package de.scoopgmbh.orchestration;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2011-10-12T09:59:54.813+02:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://orchestration.scoopgmbh.de/", name = "OrchestrationService")
@XmlSeeAlso({ObjectFactory.class})
public interface OrchestrationService {

    @RequestWrapper(localName = "resetMailbox", targetNamespace = "http://orchestration.scoopgmbh.de/", className = "de.scoopgmbh.orchestration.ResetMailbox")
    @WebMethod
    @ResponseWrapper(localName = "resetMailboxResponse", targetNamespace = "http://orchestration.scoopgmbh.de/", className = "de.scoopgmbh.orchestration.ResetMailboxResponse")
    public void resetMailbox(
        @WebParam(name = "customername", targetNamespace = "")
        java.lang.String customername
    );
}
