
/*
 * Copyright 2002-2012 SCOOP Software GmbH
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package de.scoopgmbh.orchestration;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2011-10-12T09:59:54.802+02:00
 * Generated source version: 2.4.2
 * 
 */

@javax.jws.WebService(
                      serviceName = "OrchestrationService",
                      portName = "OrchestrationServicePort",
                      targetNamespace = "http://orchestration.scoopgmbh.de/",
                      wsdlLocation = "file:wsdl/Orchestration.wsdl",
                      endpointInterface = "de.scoopgmbh.orchestration.OrchestrationService")
                      
public class OrchestrationServiceImpl implements OrchestrationService {

    private static final Logger LOG = Logger.getLogger(OrchestrationServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see de.scoopgmbh.orchestration.OrchestrationService#resetMailbox(java.lang.String  customername )*
     */
    public void resetMailbox(java.lang.String customername) { 
        LOG.info("Executing operation resetMailbox");
        System.out.println(customername);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
