<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="OrchestrationService"
	targetNamespace="http://orchestration.scoopgmbh.de/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:tns="http://orchestration.scoopgmbh.de/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
	
	<wsdl:types>
		<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://orchestration.scoopgmbh.de/" attributeFormDefault="unqualified" elementFormDefault="unqualified" targetNamespace="http://orchestration.scoopgmbh.de/">
		
			<xs:element name="createSubscription" type="tns:createSubscription" />
			<xs:element name="createSubscriptionResponse" type="tns:createSubscriptionResponse" />

			<xs:complexType name="createSubscription">
				<xs:sequence>
					<xs:element minOccurs="1" maxOccurs="1" name="msisdn" type="xs:string" />
					<xs:element minOccurs="1" maxOccurs="1" name="subscriptionTemplateId" type="xs:string" />
				</xs:sequence>
			</xs:complexType>
			
			<xs:complexType name="createSubscriptionResponse">
			</xs:complexType>
			
		</xs:schema>
	</wsdl:types>

	<wsdl:message name="createSubscriptionResponse">
		<wsdl:part name="parameters" element="tns:createSubscriptionResponse">
		</wsdl:part>
	</wsdl:message>
	<wsdl:message name="createSubscription">
		<wsdl:part name="parameters" element="tns:createSubscription">
		</wsdl:part>
	</wsdl:message>

	<wsdl:portType name="OrchestrationService">
		<wsdl:operation name="createSubscription">
			<wsdl:input name="createSubscription" message="tns:createSubscription">
			</wsdl:input>
			<wsdl:output name="createSubscriptionResponse" message="tns:createSubscriptionResponse">
			</wsdl:output>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="OrchestrationServiceSoapBinding" type="tns:OrchestrationService">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="createSubscription">
			<soap:operation soapAction="http://orchestration.scoopgmbh.de/createSubscription" style="document" />
			<wsdl:input>
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="OrchestrationService">
		<wsdl:port name="OrchestrationServicePort" binding="tns:OrchestrationServiceSoapBinding">
			<soap:address location="http://localhost:9090/OrchestrationServicePort" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
