version = 8.1.0-SNAPSHOT

org.gradle.console = plain

oss-releases.url = https://oss.sonatype.org/index.html#stagingRepositories

asmVersion = 9.10.1

springVersion = 6.2.11
springBatchVersion = 5.2.3

c3p0Version = 0.11.2
guavaVersion = 33.7.1-jre
jacksonVersion = 2.22.2
snakeyamlVersion = 1.33
commonsIoVersion = 2.22.0
commonsLangVersion = 3.20.0

slf4jVersion = 2.0.17
logbackVersion = 1.5.19

junitVersion = 6.1.3
mockitoVersion = 5.23.0
byteBuddyVersion = 1.18.14
hamcrestVersion = 3.0

jgitVersion = 7.8.0.202609011348-r

derbyVersion = 10.17.1.0
mysqlVersion = 8.0.33
postgresqlVersion = 9.1-901-1.jdbc4
cassandraAllVersion = 5.0.5
cassandraUnitVersion = 4.3.1.0
h2Version = 2.5.250

javaparserVersion = 3.28.2

