<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="OrchestrationService"
	targetNamespace="http://orchestration.copperengine.org/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:tns="http://orchestration.copperengine.org/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
	
	<wsdl:types>
		<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://orchestration.copperengine.org/" attributeFormDefault="unqualified" elementFormDefault="unqualified" targetNamespace="http://orchestration.copperengine.org/">
		
			<xs:element name="resetMailbox" type="tns:resetMailbox" />
			<xs:element name="resetMailboxResponse" type="tns:resetMailboxResponse" />

			<xs:complexType name="resetMailbox">
				<xs:sequence>
					<xs:element minOccurs="1" maxOccurs="1" name="msisdn" type="xs:string" />
					<xs:element minOccurs="1" maxOccurs="1" name="secret" type="xs:string" />
				</xs:sequence>
			</xs:complexType>
			
			<xs:complexType name="resetMailboxResponse">
			</xs:complexType>
			
		</xs:schema>
	</wsdl:types>

	<wsdl:message name="resetMailboxResponse">
		<wsdl:part name="parameters" element="tns:resetMailboxResponse">
		</wsdl:part>
	</wsdl:message>
	<wsdl:message name="resetMailbox">
		<wsdl:part name="parameters" element="tns:resetMailbox">
		</wsdl:part>
	</wsdl:message>

	<wsdl:portType name="OrchestrationService">
		<wsdl:operation name="resetMailbox">
			<wsdl:input name="resetMailbox" message="tns:resetMailbox">
			</wsdl:input>
			<wsdl:output name="resetMailboxResponse" message="tns:resetMailboxResponse">
			</wsdl:output>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="OrchestrationServiceSoapBinding" type="tns:OrchestrationService">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="resetMailbox">
			<soap:operation soapAction="http://orchestration.copperengine.org/resetMailbox" style="document" />
			<wsdl:input>
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="OrchestrationService">
		<wsdl:port name="OrchestrationServicePort" binding="tns:OrchestrationServiceSoapBinding">
			<soap:address location="http://localhost:9090/OrchestrationServicePort" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
