CREATE OR REPLACE PACKAGE COP_COREENGINE AS

PROCEDURE enqueue(i_MAX IN NUMBER, o_ROWCOUNT OUT NUMBER);

PROCEDURE restart(i_WORKFLOW_INSTANCE_ID IN VARCHAR2);

PROCEDURE restart_all;

PROCEDURE trigger_failover(i_FAILED_ENGINE_ID IN VARCHAR);

/*
PROCEDURE do_heartbeat(i_ENGINE_ID IN VARCHAR);
*/

END;
/
