CREATE USER COPPER2 IDENTIFIED BY COPPER2
  DEFAULT TABLESPACE USERS
  PROFILE DEFAULT;

GRANT CONNECT TO COPPER2;
GRANT RESOURCE TO COPPER2;
ALTER USER COPPER2 DEFAULT ROLE CONNECT,RESOURCE;
ALTER USER COPPER2 QUOTA UNLIMITED ON USERS;

grant create view to COPPER2;
GRANT EXECUTE ON DBMS_LOCK TO COPPER2;


