CREATE TABLE "TEMPLATE"
(
   WORKFLOWID varchar2(128) NOT NULL,
   ENTITYID   varchar2(128) NOT NULL,
   /*BEGINCOLUMNS*/
   NAME  varchar2(200),
   INTVALUE decimal(9)/*ENDCOLUMNS*/
   , CONSTRAINT PK_TEMPLATE PRIMARY KEY ( WORKFLOWID, ENTTIYID )
);

