
/*
 * Copyright 2002-2012 SCOOP Software GmbH
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package de.scoopgmbh.customerservice;

import java.util.logging.Logger;
import java.util.concurrent.Future;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.Response;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2011-10-12T09:59:16.188+02:00
 * Generated source version: 2.4.2
 * 
 */

@javax.jws.WebService(
                      serviceName = "CustomerServiceService",
                      portName = "CustomerServicePort",
                      targetNamespace = "http://customerservice.scoopgmbh.de/",
                      wsdlLocation = "file:wsdl/CustomerService.wsdl",
                      endpointInterface = "de.scoopgmbh.customerservice.CustomerService")
                      
public class CustomerServiceImpl implements CustomerService {

    private static final Logger LOG = Logger.getLogger(CustomerServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see de.scoopgmbh.customerservice.CustomerService#resetMailboxAsync(int  customerId )*
     */
    public Response<de.scoopgmbh.customerservice.ResetMailboxResponse> resetMailboxAsync(int customerId) { 
       return null;
       /* not called */
    }

    /* (non-Javadoc)
     * @see de.scoopgmbh.customerservice.CustomerService#resetMailboxAsync(int  customerId ,)AsyncHandler<de.scoopgmbh.customerservice.ResetMailboxResponse>  asyncHandler )*
     */
    public Future<?> resetMailboxAsync(int customerId,AsyncHandler<de.scoopgmbh.customerservice.ResetMailboxResponse> asyncHandler) { 
       return null;
       /* not called */
    }

    /* (non-Javadoc)
     * @see de.scoopgmbh.customerservice.CustomerService#resetMailbox(int  customerId )*
     */
    public void resetMailbox(int customerId) throws NoSuchCustomerException    { 
        LOG.info("Executing operation resetMailbox");
        System.out.println(customerId);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new NoSuchCustomerException("NoSuchCustomerException...");
    }

    /* (non-Javadoc)
     * @see de.scoopgmbh.customerservice.CustomerService#getCustomersByNameAsync(java.lang.String  name )*
     */
    public Response<de.scoopgmbh.customerservice.GetCustomersByNameResponse> getCustomersByNameAsync(java.lang.String name) { 
       return null;
       /* not called */
    }

    /* (non-Javadoc)
     * @see de.scoopgmbh.customerservice.CustomerService#getCustomersByNameAsync(java.lang.String  name ,)AsyncHandler<de.scoopgmbh.customerservice.GetCustomersByNameResponse>  asyncHandler )*
     */
    public Future<?> getCustomersByNameAsync(java.lang.String name,AsyncHandler<de.scoopgmbh.customerservice.GetCustomersByNameResponse> asyncHandler) { 
       return null;
       /* not called */
    }

    /* (non-Javadoc)
     * @see de.scoopgmbh.customerservice.CustomerService#getCustomersByName(java.lang.String  name )*
     */
    public de.scoopgmbh.customerservice.Customer getCustomersByName(java.lang.String name) throws NoSuchCustomerException    { 
        LOG.info("Executing operation getCustomersByName");
        System.out.println(name);
        try {
            de.scoopgmbh.customerservice.Customer _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new NoSuchCustomerException("NoSuchCustomerException...");
    }

}
