
/*
 * Copyright 2002-2012 SCOOP Software GmbH
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package de.scoopgmbh.customerservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import java.util.concurrent.Future;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.Response;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2011-10-12T09:59:16.154+02:00
 * Generated source version: 2.4.2
 * 
 */
public final class CustomerService_CustomerServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://customerservice.scoopgmbh.de/", "CustomerServiceService");

    private CustomerService_CustomerServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = CustomerServiceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        CustomerServiceService ss = new CustomerServiceService(wsdlURL, SERVICE_NAME);
        CustomerService port = ss.getCustomerServicePort();  
        
        {
        System.out.println("Invoking resetMailboxAsync...");
        int _resetMailboxAsync_customerId = 0;
        Response<de.scoopgmbh.customerservice.ResetMailboxResponse> _resetMailboxAsync__return = port.resetMailboxAsync(_resetMailboxAsync_customerId);
        System.out.println("resetMailboxAsync.result=" + _resetMailboxAsync__return);


        }
        {
        System.out.println("Invoking resetMailboxAsync...");
        int _resetMailboxAsync_customerId = 0;
        AsyncHandler<de.scoopgmbh.customerservice.ResetMailboxResponse> _resetMailboxAsync_asyncHandler = null;
        Future<?> _resetMailboxAsync__return = port.resetMailboxAsync(_resetMailboxAsync_customerId, _resetMailboxAsync_asyncHandler);
        System.out.println("resetMailboxAsync.result=" + _resetMailboxAsync__return);


        }
        {
        System.out.println("Invoking resetMailbox...");
        int _resetMailbox_customerId = 0;
        try {
            port.resetMailbox(_resetMailbox_customerId);

        } catch (NoSuchCustomerException e) { 
            System.out.println("Expected exception: NoSuchCustomerException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getCustomersByNameAsync...");
        java.lang.String _getCustomersByNameAsync_name = "";
        Response<de.scoopgmbh.customerservice.GetCustomersByNameResponse> _getCustomersByNameAsync__return = port.getCustomersByNameAsync(_getCustomersByNameAsync_name);
        System.out.println("getCustomersByNameAsync.result=" + _getCustomersByNameAsync__return);


        }
        {
        System.out.println("Invoking getCustomersByNameAsync...");
        java.lang.String _getCustomersByNameAsync_name = "";
        AsyncHandler<de.scoopgmbh.customerservice.GetCustomersByNameResponse> _getCustomersByNameAsync_asyncHandler = null;
        Future<?> _getCustomersByNameAsync__return = port.getCustomersByNameAsync(_getCustomersByNameAsync_name, _getCustomersByNameAsync_asyncHandler);
        System.out.println("getCustomersByNameAsync.result=" + _getCustomersByNameAsync__return);


        }
        {
        System.out.println("Invoking getCustomersByName...");
        java.lang.String _getCustomersByName_name = "";
        try {
            de.scoopgmbh.customerservice.Customer _getCustomersByName__return = port.getCustomersByName(_getCustomersByName_name);
            System.out.println("getCustomersByName.result=" + _getCustomersByName__return);

        } catch (NoSuchCustomerException e) { 
            System.out.println("Expected exception: NoSuchCustomerException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
