CREATE USER COPPER IDENTIFIED BY COPPER
  DEFAULT TABLESPACE USERS
  PROFILE DEFAULT;

GRANT CONNECT TO COPPER;
GRANT RESOURCE TO COPPER;
GRANT EXECUTE ON DBMS_LOCK TO COPPER;

ALTER USER COPPER DEFAULT ROLE CONNECT,RESOURCE;
ALTER USER COPPER QUOTA UNLIMITED ON USERS;



